import { MODEL_LIBRARY } from './library.js';
import { MALWARE_PRESETS,createVirtualFiles,infectFiles,scanVirtualFiles,restoreVirtualFiles,inspectCode,validateVirus,validateRules } from './core.js';
import { API_BASE } from './config.js';
import { mountTypingBoard } from './typer.js';
import { renderIntroDetails,mountIntroMotion } from './intro.js';
import { mountBackgroundMusic } from './bgm.js';
const backgroundMusic = mountBackgroundMusic(document.querySelector('#bgm-player'));
const apiBase=location.hostname==='127.0.0.1'||location.hostname==='localhost'?'':API_BASE;
const $=(s,root=document)=>root.querySelector(s);
const icons={scan:'<path d="M8 3H3v5m13-5h5v5M3 16v5h5m8 0h5v-5"/><circle cx="12" cy="11" r="4"/><path d="m15 14 4 4"/>',terminal:'<rect x="3" y="4" width="18" height="16" rx="1"/><path d="m7 9 3 3-3 3m6 0h4"/>',file:'<path d="M14 3H5v18h14V8l-5-5v5h5M8 12h8m-8 4h6"/>',book:'<path d="M12 5c-3-2-7-2-10-1v15c3-1 7-1 10 1 3-2 7-2 10-1V4c-3-1-7-1-10 1v15"/>',flag:'<path d="M5 21V3m0 1c5-4 9 4 14 0v10c-5 4-9-4-14 0"/>',external:'<path d="M14 3h7v7m0-7L10 14M10 3H3v18h18v-7"/>',menu:'<path d="M3 6h18M3 12h18M3 18h18"/>',link:'<path d="m10 14 4-4M8 16l-1 1a4 4 0 0 1-6-6l5-5a4 4 0 0 1 6 0m0 12a4 4 0 0 1 0-6l5-5a4 4 0 0 1 6 6l-1 1"/>',shield:'<path d="m12 2 8 4v7c0 5-8 9-8 9s-8-4-8-9V6l8-4"/><path d="m8 12 3 3 5-6"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',chevron:'<path d="m9 5 7 7-7 7"/>',check:'<path d="m5 12 4 4L19 6"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',target:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',activity:'<path d="M2 12h4l3-8 6 16 3-8h4"/>',code:'<path d="m8 6-6 6 6 6m8-12 6 6-6 6M14 3l-4 18"/>',globe:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18M5 7h14M5 17h14"/>',play:'<path d="m7 4 14 8-14 8V4"/>',refresh:'<path d="M20 10a8 8 0 1 0-2 8M20 4v6h-6"/>',desktop:'<rect x="2" y="3" width="20" height="14" rx="1"/><path d="M12 17v4m-5 0h10"/>',mobile:'<rect x="7" y="2" width="10" height="20" rx="2"/><path d="M11 18h2"/>',expand:'<path d="M8 3H3v5m13-5h5v5M3 16v5h5m8 0h5v-5"/>',save:'<path d="M4 3h14l3 3v15H3V3h1M7 3v6h10V3M7 21v-8h10v8"/>',bug:'<path d="M8 9h8v7a4 4 0 0 1-8 0V9m2 0V6h4v3M5 6l3 3m8 0 3-3M3 12h5m8 0h5M4 19l4-3m8 0 4 3M12 9v10"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'};
const icon=name=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.code}</svg>`;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function decorate(){document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));}
let toastTimer;function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
function openDialog(content,label='HEXLAB / INTELLIGENCE'){$('#dialog-content').innerHTML=content;$('#dialog-eyebrow').textContent=label;$('#detail-dialog').showModal();$('#dialog-content').scrollTop=0;}
$('#dialog-close').onclick=()=>$('#detail-dialog').close();$('#detail-dialog').onclick=e=>{if(e.target===$('#detail-dialog'))$('#detail-dialog').close();};
const demoIssues=[
 {id:'runtime',severity:'critical',title:'Outdated PHP Version',description:'지원이 종료된 PHP 버전이 사용되고 있습니다.',evidence:'데모 응답: X-Powered-By: PHP/7.4.3',fix:'지원되는 PHP 버전으로 업그레이드하고 회귀 테스트를 수행하세요.'},
 {id:'headers',severity:'high',title:'Missing Security Headers',description:'CSP, X-Frame-Options 보안 헤더가 누락되었습니다.',evidence:'데모 응답에 Content-Security-Policy, X-Frame-Options 없음',fix:'CSP 정책과 frame-ancestors 또는 X-Frame-Options를 설정하세요.'},
 {id:'xss',severity:'high',title:'Potential Reflected XSS',description:'사용자 입력이 검증 없이 출력되는 연습 시나리오입니다.',evidence:'데모 시나리오: innerHTML에 사용자 입력 직접 삽입',fix:'textContent를 사용하고 출력 맥락에 맞게 인코딩하세요.'},
 {id:'cookie',severity:'medium',title:'Cookie Missing Secure Flag',description:'쿠키의 Secure 속성이 설정되지 않았습니다.',evidence:'데모 응답: Set-Cookie: session=demo; Path=/',fix:'세션 쿠키에 Secure, HttpOnly와 적절한 SameSite 속성을 설정하세요.'},
 {id:'listing',severity:'medium',title:'Directory Listing Enabled',description:'디렉터리 파일 목록이 노출되는 연습 시나리오입니다.',evidence:'데모 시나리오: /uploads/ 디렉터리 인덱스',fix:'웹 서버의 디렉터리 인덱스 설정을 비활성화하세요.'},
 {id:'library',severity:'medium',title:'Legacy JavaScript Library',description:'오래된 라이브러리를 사용하는 연습 시나리오입니다.',evidence:'데모 문서: jquery-3.4.1.min.js',fix:'사용하는 의존성의 보안 공지를 확인하고 검증된 버전으로 업데이트하세요.'},
 {id:'hsts',severity:'low',title:'No HSTS Header',description:'HTTPS 연결을 강제하는 정책이 설정되지 않았습니다.',evidence:'데모 응답: Strict-Transport-Security 없음',fix:'HTTPS가 정상 동작하는지 확인한 뒤 HSTS 정책을 추가하세요.'}
];
const demoReport={demo:true,url:'https://example.com',finalUrl:'https://example.com',score:72,grade:'B',risk:'MODERATE',status:200,server:'cloudflare',title:'Example website',elapsed:1.24,scannedAt:'2026-10-04T14:32:18Z',issues:demoIssues,technologies:['Nginx','PHP','jQuery','Cloudflare'],checks:[{name:'HTTPS',result:'사용',detail:'TLS 연결'},{name:'HTTP response',result:'200 OK',detail:'정상 응답'},{name:'Redirect',result:'HTTPS',detail:'보안 연결'},{name:'Content type',result:'text/html',detail:'웹 문서'}]};
let report=demoReport;let issueFilter='all';let historyReports=[];try{historyReports=JSON.parse(localStorage.getItem('hexlab-reports')||'[]').slice(0,12);}catch{}let page='scan';let labMode=location.hash.includes('/lab/bio')?'bio':'web';
function heading(kicker,title,description,badge){return `<div class="page-heading"><div><div class="eyebrow">${kicker}</div><h1><span class="terminal-chevron">&gt;</span>${title}</h1><p>${description}</p></div>${badge?`<div class="header-badge">${badge}</div>`:''}</div>`;}
function panelHeader(title,ico,right=''){return `<div class="panel-header"><h2>${icon(ico)}${title}</h2>${right}</div>`;}
function renderScan(){
 $('#main-content').innerHTML=heading('01 / RECONNAISSANCE','ANALYZE ANY WEBSITE.','URL 하나로 시작하는 보안 점검. 취약점을 발견하고, 더 안전한 웹을 만드세요.','<span class="signal-dot"></span>PASSIVE SECURITY SCAN')+`
 <form id="scan-form" class="input-panel"><label class="input-label" for="scan-url">TARGET URL</label><div class="input-wrap">${icon('link')}<input id="scan-url" type="url" required placeholder="https://example.com" value="${esc(report.url)}" aria-label="분석할 웹사이트 URL" spellcheck="false"></div><button class="primary-button" id="scan-button" type="submit">${icon('scan')}보안 분석 시작${icon('arrow')}</button><div class="scan-progress"><i></i></div></form>
 <div class="input-help"><span>${icon('shield')}공개 페이지의 HTTP 응답과 보안 헤더를 확인합니다. 공격 요청은 전송하지 않습니다.</span><button class="text-link" id="demo-button">DEMO TARGET ${icon('external')}</button></div><div class="error-message" id="scan-error" role="alert"></div><div id="scan-results"></div>`;
 renderResults();$('#scan-form').onsubmit=async e=>{e.preventDefault();await runScan($('#scan-url').value);};$('#demo-button').onclick=()=>{report=demoReport;issueFilter='all';renderScan();toast('샘플 리포트입니다. 실제 분석 결과가 아닙니다.');};
}
function renderResults(){const r=report;const stamp=new Date(r.scannedAt).toLocaleString('sv-SE',{timeZone:'Asia/Seoul'});const counts=['critical','high','medium','low','info'].map(s=>({name:s,count:r.issues.filter(i=>i.severity===s).length}));const filtered=r.issues.filter(i=>issueFilter==='all'||i.severity===issueFilter);
 $('#scan-results').innerHTML=`<div class="scan-status"><div class="scan-status-left"><span class="status-title">${icon('check')}SCAN COMPLETE</span>${r.demo?'<span class="demo-pill">DEMO REPORT</span>':''}<span>${esc(new URL(r.url).hostname)}</span><span class="meta-divider">|</span><span>${stamp} KST</span><span class="meta-divider">|</span><span>${r.elapsed.toFixed(2)}s elapsed</span></div><div class="report-id"><span>RPT-${r.demo?'DEMO':Date.parse(r.scannedAt).toString(36).toUpperCase()}</span><button class="icon-button" id="download-report" aria-label="리포트 다운로드">${icon('download')}</button></div></div>
 <div class="overview-grid"><section class="panel">${panelHeader('SECURITY SCORE','shield','<span class="panel-code">[ 01 ]</span>')}<div class="score-body"><div class="score-ring"><svg viewBox="0 0 120 120"><circle class="ring-track" cx="60" cy="60" r="52"/><circle class="ring-value" cx="60" cy="60" r="52" style="stroke-dashoffset:${326.73*(1-r.score/100)}"/></svg><div class="score-number"><strong>${r.score}</strong><span>/ 100 POINTS</span></div></div><div class="score-description"><div class="grade">${esc(r.grade)}<span style="font-size:22px">${r.grade==='B'?'+':''}</span></div><div><div class="risk-caption">RISK LEVEL</div><div class="risk-value">${esc(r.risk)}</div></div><p>${r.demo?'보완이 필요한 항목이 있습니다.<br>아래 권고 사항을 확인하세요.':'공개 응답 기준의 점수입니다.<br>전체 보안 수준을 보증하지 않습니다.'}</p></div></div></section>
 <section class="panel">${panelHeader('TARGET INFORMATION','target','<span class="panel-code">[ 02 ]</span>')}<div class="info-table">${[['URL',new URL(r.finalUrl).hostname],['Protocol',new URL(r.finalUrl).protocol==='https:'?'HTTPS / TLS':'HTTP'],['HTTP Status',String(r.status)],['Server',r.server||'Not disclosed'],['Technologies',r.technologies.length?r.technologies.join(', '):'확인되지 않음'],['Scan Method',r.demo?'Sample data':'Passive HTTP']].map(([k,v])=>`<div class="info-row"><span>${k}</span><span>${esc(v)}</span></div>`).join('')}</div></section>
 <section class="panel">${panelHeader('ISSUE SUMMARY','activity','<span class="panel-code">[ 03 ]</span>')}<div class="summary-list"><div class="summary-total"><span>Total issues</span><strong>${r.issues.length.toString().padStart(2,'0')}</strong></div>${counts.map(c=>`<div class="severity-row ${c.name}"><span class="severity-dot"></span><span class="severity-name">${c.name[0].toUpperCase()+c.name.slice(1)}</span><span class="severity-count">${c.count.toString().padStart(2,'0')}</span></div>`).join('')}</div></section></div>
 <div class="results-grid"><section class="panel">${panelHeader('VULNERABILITIES','bug',`<div class="vuln-filter"><button class="filter-button ${issueFilter==='all'?'active':''}" data-filter="all">ALL</button><button class="filter-button ${issueFilter==='high'?'active':''}" data-filter="high">HIGH</button><button class="filter-button ${issueFilter==='medium'?'active':''}" data-filter="medium">MED</button></div>`)}<div class="vulnerability-list">${filtered.length?filtered.map(i=>`<button class="vulnerability" data-issue="${esc(i.id)}"><span class="severity-label ${i.severity}"><b>+</b>${i.severity.toUpperCase()}</span><span class="vuln-copy"><span class="vuln-title">${esc(i.title)}</span><span class="vuln-desc">${esc(i.description)}</span></span>${icon('chevron')}</button>`).join(''):'<div class="empty-state">이 필터에서 발견된 항목이 없습니다.</div>'}</div></section>
 <div class="right-stack"><section class="panel">${panelHeader('CONNECTION STATUS','globe','<span class="panel-code">HTTP INSPECTION</span>')}<div class="endpoint-table"><div class="table-line table-head"><span>CHECK</span><span>DETAIL</span><span>STATUS</span></div>${r.checks.map(c=>`<div class="table-line"><span>${esc(c.name)}</span><span>${esc(c.detail)}</span><span class="state-text"><span class="signal-dot"></span>${esc(c.result)}</span></div>`).join('')}</div></section>
 <section class="panel">${panelHeader('TECHNOLOGY STACK','code',`<button class="text-link" id="tech-details">VIEW DETAILS ${icon('chevron')}</button>`)}<div class="tech-list">${(r.technologies.length?r.technologies:['Unknown']).map((t,i)=>`<div class="tech-item"><span class="tech-logo">${esc(t[0])}</span><span>${esc(t)}<small>${['WEB SERVER','RUNTIME','FRONTEND','EDGE NETWORK'][i%4]}</small></span></div>`).join('')}</div></section>
 <section class="panel">${panelHeader('RECOMMENDATIONS','check',`<button class="text-link" id="full-report">FULL REPORT ${icon('chevron')}</button>`)}<ol class="recommendations">${r.issues.slice(0,4).map(i=>`<li>${esc(i.fix)}</li>`).join('')||'<li>관측된 헤더 누락이 없습니다. 추가 수동 점검을 권장합니다.</li>'}</ol><div class="recommendation-note">${r.demo?'샘플 데이터를 이용한 데모 리포트 · 실제 대상의 취약점이 아닙니다.':'서버 내부, 인증 흐름과 실제 공격 가능성은 별도 점검이 필요합니다.'}</div></section></div></div><div class="page-bottom-note"><span>// KNOW THE RISKS. <strong>TAKE CONTROL.</strong></span><span>${r.demo?'DEMO ENVIRONMENT':'PUBLIC RESPONSE ANALYSIS'} <span style="color:var(--green)">_</span></span></div>`;
 $('[id="download-report"]').onclick=downloadReport;$('#full-report').onclick=()=>openDialog(`<span class="demo-pill">${r.demo?'DEMO DATA':'PASSIVE HTTP REPORT'}</span><h2>보안 분석 리포트</h2><p>${esc(r.url)} · ${r.score}/100 · ${r.issues.length}개 발견 항목</p><pre>${esc(JSON.stringify(r,null,2))}</pre><button class="primary-button" id="dialog-download">${icon('download')}JSON 다운로드</button>`);$('#full-report').addEventListener('click',()=>$('#dialog-download').onclick=downloadReport);
 $('#tech-details').onclick=()=>openDialog(`<h2>관측된 기술 스택</h2><p>${r.demo?'샘플 리포트의 기술 정보입니다.':'응답 헤더와 HTML에서 발견된 문자열을 기준으로 추정합니다. 버전의 안전성은 별도 확인이 필요합니다.'}</p><pre>${esc(r.technologies.join('\n')||'기술 정보를 확인할 수 없습니다.')}</pre>`);
 document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{issueFilter=b.dataset.filter;renderResults();});document.querySelectorAll('[data-issue]').forEach(b=>b.onclick=()=>showIssue(report.issues.find(i=>i.id===b.dataset.issue)));
}
function showIssue(i){openDialog(`<span class="severity-label ${i.severity}" style="display:inline-flex">${i.severity.toUpperCase()}</span><h2>${esc(i.title)}</h2><p>${esc(i.description)}</p><h3>OBSERVED EVIDENCE</h3><pre>${esc(i.evidence)}</pre><h3>RECOMMENDED FIX</h3><p>${esc(i.fix)}</p>${report.demo?'<p>이 항목은 학습용 샘플입니다. 실제 URL에 대한 취약점으로 판정한 결과가 아닙니다.</p>':''}`,'HEXLAB / VULNERABILITY DETAIL');}
function download(data,name,type='application/json'){const a=document.createElement('a');const u=URL.createObjectURL(new Blob([data],{type}));a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function downloadReport(){download(JSON.stringify(report,null,2),'hexlab-report.json');toast('분석 리포트를 다운로드했습니다.');}
async function api(path,data){try{const res=await fetch(apiBase+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data),signal:AbortSignal.timeout(60000)});const result=await res.json();if(!res.ok)throw new Error(result.error||'요청을 처리할 수 없습니다.');return result;}catch(e){if(e instanceof TypeError)throw new Error('분석 서버에 연결할 수 없습니다. 잠시 후 다시 시도하세요.');throw e;}}
async function runScan(value){const form=$('#scan-form');const btn=$('#scan-button');if(!form)return;form.classList.add('scanning');btn.disabled=true;btn.textContent='ANALYZING...';$('#scan-error').style.display='none';try{const data=await api('/api/scan',{url:value});report=data;issueFilter='all';historyReports.unshift(data);historyReports=historyReports.slice(0,12);try{localStorage.setItem('hexlab-reports',JSON.stringify(historyReports));}catch{}markMission('scan');$('#report-count').textContent=String(historyReports.length).padStart(2,'0');if(page==='scan')renderResults();toast('공개 응답에 대한 보안 분석을 완료했습니다.');return data;}catch(e){if($('#scan-error')){$('#scan-error').textContent=e.message;$('#scan-error').style.display='block';}return{error:e.message};}finally{form.classList.remove('scanning');btn.disabled=false;btn.innerHTML=`${icon('scan')}보안 분석 시작${icon('arrow')}`;}}
function markMission(name){$('#mission-'+name).checked=true;saveMissions();}
function saveMissions(){const values=['scan','edit','av'].map(s=>$('#mission-'+s).checked);try{localStorage.setItem('hexlab-missions',JSON.stringify(values));}catch{}$('#mission-progress').style.width=values.filter(Boolean).length/3*100+'%';$('#mission-caption').textContent=values.filter(Boolean).length+' / 3 COMPLETE';}
try{JSON.parse(localStorage.getItem('hexlab-missions')||'[]').forEach((v,i)=>{if(['scan','edit','av'][i])$('#mission-'+['scan','edit','av'][i]).checked=!!v;});}catch{}document.querySelectorAll('.sidebar-mission input').forEach(i=>i.onchange=saveMissions);saveMissions();
let disposeTypingBoard=()=>{},disposeIntroMotion=()=>{};
function navigate(route,push=true){disposeIntroMotion();disposeIntroMotion=()=>{};disposeTypingBoard();disposeTypingBoard=()=>{};window.scrollTo({top:0,behavior:'instant'});page=route;if(push)history.pushState({},'','#/'+(route==='intro'?'':route==='lab'?'lab/'+labMode:route));document.body.classList.toggle('intro-mode',route==='intro');document.body.classList.toggle('code-mode',route==='code');document.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===route));$('#lab-subnav').hidden=route!=='lab';$('#breadcrumb-page').textContent=route==='intro'?'ACCESS TERMINAL':route==='lab'?'SIMULATION LAB':route==='code'?'CODE TERMINAL':'SECURITY SCAN';$('#sidebar').classList.remove('open');if(route==='lab')renderLab();else if(route==='intro')renderIntro();else if(route==='code')renderTypingPage();else renderScan();backgroundMusic.setPage(route,labMode);}
function routeFromLocation(){const path=location.hash?location.hash.slice(1):location.pathname;if(/\/lab\/bio(?:\/|$)/.test(path))labMode='bio';else if(/\/lab\/web(?:\/|$)/.test(path))labMode='web';return /\/lab(?:\/|$)/.test(path)?'lab':/\/scan(?:\/|$)/.test(path)?'scan':/\/code(?:\/|$)/.test(path)?'code':'intro';}
document.querySelectorAll('[data-route]').forEach(a=>a.onclick=e=>{e.preventDefault();navigate(a.dataset.route);});window.onpopstate=window.onhashchange=()=>navigate(routeFromLocation(),false);$('.brand').onclick=e=>{e.preventDefault();navigate('intro');};$('#menu-toggle').onclick=()=>$('#sidebar').classList.toggle('open');
$('#history-nav').onclick=()=>{openDialog(`<h2>분석 리포트</h2><p>이 브라우저에 저장한 최근 분석입니다.</p>${historyReports.length?historyReports.map((r,i)=>`<div class="history-item"><span>${esc(new URL(r.url).hostname)}<small style="display:block;color:var(--muted)">${new Date(r.scannedAt).toLocaleString('ko-KR')} · ${r.score}점</small></span><button data-history="${i}">리포트 열기</button></div>`).join(''):'<div class="empty-state">아직 저장된 분석이 없습니다. URL을 입력해 첫 분석을 시작하세요.</div>'}`,'HEXLAB / LOCAL REPORTS');document.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>{report=historyReports[+b.dataset.history];issueFilter='all';$('#detail-dialog').close();navigate('scan');});};
$('#guide-nav').onclick=()=>openDialog('<h2>보안 플레이북</h2><h3>01 / 응답 헤더 읽기</h3><p>CSP는 허용된 콘텐츠 출처를 제한합니다. HSTS는 HTTPS 사용을 강제합니다. X-Content-Type-Options: nosniff는 MIME 타입 추측을 막습니다.</p><h3>02 / 입력과 출력 분리</h3><p>사용자 입력을 화면에 보여줄 때 textContent를 사용하세요. SQL 쿼리는 매개변수화하고, HTML이 꼭 필요할 때는 검증된 정화 도구를 사용하세요.</p><h3>03 / 관측과 검증</h3><p>헤더 누락이 곧 공격 성공을 의미하지는 않습니다. 대상 환경과 인증 흐름, 실제 영향까지 검증해야 합니다.</p><h3>04 / 바이러스 & 백신 실험</h3><p>실습실은 가상 파일로 동작합니다. 표시자를 넣어 감염을 표현하고, 탐지 규칙으로 표시자를 발견해 격리·복구하는 과정을 배워보세요.</p>','HEXLAB / SECURITY PLAYBOOK');
$('#mission-nav').onclick=()=>openDialog('<h2>오늘의 미션</h2><ol><li>보안 분석 페이지에서 공개 웹사이트 URL을 점검하세요.</li><li>모의해킹 실습에서 제목이나 색상을 바꾸고 미리보기에 적용하세요.</li><li>바이러스 & 백신 실험실에서 탐지 규칙을 작성하고 가상 파일을 검사하세요.</li></ol><p>완료한 미션은 왼쪽 체크리스트에 저장됩니다.</p>','HEXLAB / DAILY MISSIONS');
function renderTypingPage(){
 $('#main-content').innerHTML=`<div class="page-heading"><div><div class="eyebrow">03 / CODE THEATRE</div><h1><span class="terminal-chevron">&gt;</span>해킹 코드 삽입.</h1><p>어떤 키를 눌러도, 당신의 손끝에서 코드가 쏟아집니다.</p></div><div class="header-badge"><span class="signal-dot"></span> VISUAL SIMULATION</div></div><section class="panel typer-panel"><div class="panel-header"><h2>${icon('terminal')} OPERATOR TERMINAL <span class="live-badge">LIVE</span></h2><div class="typer-actions"><button class="outline-button" id="typer-clear">${icon('refresh')}보드 비우기</button><button class="icon-button" id="typer-expand" aria-label="코드 보드 확대">${icon('expand')}</button></div></div><div class="typer-toolbar"><label>CODE STREAM <select id="typer-format" aria-label="코드 종류"><option value="mixed">Random mix</option><option value="python">Python</option><option value="javascript">JavaScript</option><option value="terminal">Terminal</option></select></label><label>SPEED <select id="typer-speed" aria-label="코드 출력 속도"><option value="3">Cinematic</option><option value="8" selected>Fast</option><option value="18">Turbo</option></select></label><span class="typer-session">SESSION / LOCAL_01</span></div><div class="typer-surface"><pre class="typer-code"><code id="typer-output"></code><span class="typer-cursor" aria-hidden="true">▌</span></pre><textarea id="typer-capture" aria-label="해킹 코드 보드" aria-describedby="typer-help" spellcheck="false" autocomplete="off" autocapitalize="off"></textarea></div><div class="panel-status"><span><span class="signal-dot"></span> <span id="typer-state">READY</span></span><span><b id="typer-count">0</b> CHARS <span class="footer-slash">/</span> DISPLAY ONLY</span></div></section><div class="typer-hints"><p id="typer-help">${icon('code')} 빈 보드를 클릭하고 아무 키나 입력하세요. 실제 입력 대신 랜덤한 코드가 한 줄씩 채워집니다.</p><button class="outline-button" id="typer-focus">${icon('terminal')}보드에 입력하기</button></div><div class="typer-note"><span>// THE STAGE IS YOURS.</span><p>무결성 검증, 패킷 검사, 보안 정책 등의 예제 코드를 보여주는 타이핑 연출입니다.</p></div>`;
 disposeTypingBoard=mountTypingBoard($('#main-content'));
}
function renderCodeRain(){
 const alphabet='01ABCDEF0123456789{}[]<>/\\=+*:#';
 const streams=Array.from({length:44},(_,column)=>{
  const length=18+Math.floor(Math.random()*20);
  const glyphs=Array.from({length},()=>alphabet[Math.floor(Math.random()*alphabet.length)]);
  const duration=9+Math.random()*10;
  return `<span class="code-rain-stream" style="--column:${column};--fall-duration:${duration.toFixed(2)}s;--fall-delay:${(-Math.random()*duration).toFixed(2)}s">${esc(glyphs.slice(0,-1).join('\n'))}\n<b>${esc(glyphs.at(-1))}</b></span>`;
 }).join('');
 return `<div class="intro-code-rain" aria-hidden="true">${streams}</div>`;
}
function renderIntro(){
 $('#main-content').innerHTML=`${renderCodeRain()}<div class="intro-container"><div class="intro-topline"><a class="intro-logo" href="#/">${icon('terminal')} HEX<span>LAB</span></a><span><span class="signal-dot"></span> LEARNING ENVIRONMENT ONLINE</span></div><div class="intro-hero"><div class="intro-copy"><div class="eyebrow">// ACCESS GRANTED. WELCOME, OPERATOR.</div><h1>ENTER THE<br>SECURITY<br><span>PLAYGROUND.</span><i>_</i></h1><p>웹의 약점을 찾고, 직접 실험하고, 방어하세요.<br>당신의 다음 보안 레벨은 여기에서 시작됩니다.</p><button class="outline-button" id="intro-guide">${icon('book')}처음이라면, 이용 가이드</button><div class="intro-system"><span>ENVIRONMENT</span> ISOLATED <b>/</b> <span>LEVEL</span> BEGINNER → ADVANCED</div></div><div class="intro-visual"><img src="./anonymous.png" alt="검은 후드와 어나니머스 스타일 가면을 쓴 가상의 보안 실습 가이드"><div class="image-corner corner-tl"></div><div class="image-corner corner-br"></div><span class="visual-label">IDENTITY : ANONYMOUS<br>MISSION : A SAFER WEB</span><div class="guide-caption"><span>GUIDE_01</span><p>“먼저 분석하고, 실험하고, 방어하세요.”</p></div></div></div><div class="choose-heading" id="mission-selector"><h2><span>01</span> SELECT YOUR MISSION</h2><span>어디서부터 시작할까요?</span></div><div class="intro-cards"><button class="intro-card" data-start="scan"><div class="card-number">01 / RECONNAISSANCE ${icon('scan')}</div><h3>웹사이트 보안 분석</h3><p>URL을 입력하고 보안 헤더, 위험도,<br>개선할 항목을 확인하세요.</p><div class="intro-card-bottom"><span>SECURITY SCAN</span>${icon('arrow')}</div></button><button class="intro-card" data-start="web"><div class="card-number">02 / EXPERIMENT ${icon('code')}</div><h3>모의해킹 실습</h3><p>공개 페이지를 복제하고 코드를 편집하며<br>취약한 패턴을 찾아 수정하세요.</p><div class="intro-card-bottom"><span>WEB SANDBOX</span>${icon('arrow')}</div></button><button class="intro-card" data-start="bio"><div class="card-number">03 / DEFENSE ${icon('bug')}</div><h3>바이러스 & 백신 실험</h3><p>가상 감염 규칙과 나만의 백신을 만들고<br>실제 사례의 동작 개념을 배워보세요.</p><div class="intro-card-bottom"><span>MALWARE & ANTIVIRUS LAB</span>${icon('arrow')}</div></button><button class="intro-card" data-start="code"><div class="card-number">04 / CODE THEATRE ${icon('terminal')}</div><h3>해킹 코드 삽입</h3><p>아무 키나 입력하면 랜덤한 코드가 쏟아지는<br>나만의 해커 터미널을 열어보세요.</p><div class="intro-card-bottom"><span>HACKER TYPING BOARD</span>${icon('arrow')}</div></button></div><div class="intro-endline"><span>NO EXPERIENCE REQUIRED. JUST CURIOSITY.</span><span>실습 데이터는 이 브라우저에 저장됩니다.</span></div></div>`;
 document.querySelector('.intro-container').insertAdjacentHTML('beforeend',renderIntroDetails(icon));disposeIntroMotion=mountIntroMotion(document.querySelector('#main-content'));document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>{if(b.dataset.start==='scan')navigate('scan');else if(b.dataset.start==='code')navigate('code');else{labMode=b.dataset.start==='bio'?'bio':'web';navigate('lab');}});$('#intro-guide').onclick=()=>openDialog('<h2>당신의 첫 번째 보안 실습</h2><h3>01 / SCAN</h3><p>공개 URL을 입력하세요. 서버가 응답과 보안 헤더를 확인해 점검 결과를 보여줍니다. 처음에는 표시된 데모 리포트로 항목을 살펴보세요.</p><h3>02 / CLONE → EDIT → INSPECT</h3><p>URL을 복제하거나 예제 사이트를 선택하세요. HTML·CSS·JS를 바꾸면 미리보기에 적용됩니다. 실습 분석으로 위험한 코드 패턴을 찾아 수정하고, 프로젝트를 JSON으로 내보낼 수 있습니다.</p><h3>03 / CREATE → DETECT → RESTORE</h3><p>바이러스 규칙을 편집해 가상 파일의 감염을 표현하세요. 백신 규칙을 작성하거나 탐지 프리셋을 적용하고 검사·격리·복구해보세요. 기존 제품과 악성코드는 개념 모델이며 실제 실행 파일이나 실제 백신 엔진이 아닙니다.</p><p>공개 페이지 복제는 정적 HTML·CSS를 가져옵니다. 로그인 화면 뒤의 콘텐츠와 원본 서버 기능은 복제되지 않습니다.</p>','HEXLAB / GETTING STARTED');
}
const initialHTML=`<!DOCTYPE html>
<html lang="ko">
<head><title>NEXUS — Digital solutions</title></head>
<body>
  <header><a class="logo">NEXUS<span>®</span></a>
    <nav><a href="#home">Home</a><a href="#services">Services</a><a href="#about">About</a></nav>
    <span class="nav-status">● AVAILABLE FOR WORK</span>
  </header>
  <main id="home">
    <div class="label">INDEPENDENT DIGITAL STUDIO / EST. 2024</div>
    <h1>Better ideas.<br><em>Built different.</em></h1>
    <p>We turn complex challenges into simple,<br>beautiful digital experiences.</p>
    <button id="contact">Let's build something ↗</button>
    <div class="visual-grid"><div class="orb">N</div><span class="orbit-label">NEXT GENERATION / DESIGN & TECHNOLOGY</span></div>
    <div class="stats"><div><b>120+</b><span>PROJECTS DELIVERED</span></div><div><b>98%</b><span>CLIENT SATISFACTION</span></div><div><b>12</b><span>COUNTRIES CONNECTED</span></div></div>
  </main>
  <section id="services"><h2>Design. Develop. Deliver.</h2><p>Your next idea starts with a conversation.</p></section>
</body></html>`;
const initialCSS=`* { box-sizing: border-box; }
body { margin: 0; background: #081011; color: #e4eeec; font-family: Arial, sans-serif; }
header { display:flex; align-items:center; justify-content:space-between; padding:26px 32px; border-bottom:1px solid #23312e; }
.logo { font-size:22px; font-weight:800; letter-spacing:-1px; }.logo span { color:#39f49a; font-size:12px; vertical-align:top; }
nav { display:flex; gap:22px; }nav a { color:#a8bcb6; text-decoration:none; font-size:10px; }.nav-status { color:#4cc28c; font-size:7px; letter-spacing:1px; }
main { position:relative; overflow:hidden; padding:48px 32px 22px; }
.label { color:#779389; font-size:8px; letter-spacing:1.8px; }
h1 { position:relative; z-index:2; font-size:48px; letter-spacing:-2px; line-height:1.04; margin:24px 0 18px; }
h1 em { color:#39f49a; font-style:normal; }
main p { font-size:12px; line-height:1.8; color:#91aba2; position:relative; z-index:2; }
button { border:none; background:#39f49a; padding:13px 16px; margin-top:14px; font-size:10px; font-weight:600; position:relative; z-index:2; cursor:pointer; }
.visual-grid { position:absolute; width:200px; height:260px; right:18px; top:70px; border:1px solid #28553c; background:repeating-linear-gradient(0deg,transparent,transparent 23px,#123525 24px),repeating-linear-gradient(90deg,transparent,transparent 23px,#123525 24px); transform:perspective(700px) rotateY(-23deg); display:grid; place-items:center; }
.orb { width:140px; height:140px; border:1px solid #39f49a; background:#132e2390; color:#39f49a; border-radius:50%; display:grid; place-items:center; font-size:84px; box-shadow:0 0 50px #39f49a20; }
.orbit-label { position:absolute; bottom:12px; font-size:6px; color:#39f49a; letter-spacing:1px; }
.stats { display:flex; gap:32px; border-top:1px solid #234232; margin-top:52px; padding-top:22px; position:relative; z-index:2; }
.stats div { display:flex; flex-direction:column; }.stats b { color:#39f49a; font-size:23px; }.stats span { font-size:7px; color:#6a8c7b; margin-top:5px; }
#services { padding:20px 32px 40px; color:#a5bcb2; font-size:11px; }
@media(max-width:500px) { .visual-grid { opacity:.38; right:-70px; } h1 { font-size:40px; } .nav-status { display:none; } header { padding-inline:24px; } main { padding-inline:24px; } .stats { gap:20px; } }
`;
const initialJS=`// 실습 코드: HTML 삽입 패턴을 검사해보세요.
const button = document.querySelector('#contact');
button?.addEventListener('click', () => {
  button.innerHTML = 'Thanks! Let’s connect.';
});

// 안전한 대안: button.textContent = 'Thanks!';
`;
let project={html:initialHTML,css:initialCSS,js:initialJS,source:'예제: NEXUS Studio',originalUrl:'https://example.com',demo:true};try{const p=JSON.parse(localStorage.getItem('hexlab-project')||'null');if(p&&typeof p.html==='string'&&typeof p.css==='string'&&typeof p.js==='string')project=p;}catch{}
let appliedProject={...project};let editorTab='html';let autoApply=true;let editingTimer;let localIssues=[];let consoleLines=['HEXLAB Sandbox Console v1.0','[+] Isolated environment ready.','[i] Type help to view available commands.'];let step=2;let virtualFiles=createVirtualFiles();let selectedVirus='wannacry';let virusConfig={...MALWARE_PRESETS.wannacry};let avPreset='signature';let ruleSet=[{name:'Signature-01',type:'signature',match:'HEXLAB_DEMO',action:'quarantine'}];let bioLog=['[+] Virtual filesystem initialized. 8 files.','[i] No host files or system processes are accessed.'];let ticks=0;let avFindings=[];
function renderLab(){document.querySelectorAll('[data-lab-mode]').forEach(b=>b.classList.toggle('active',b.dataset.labMode===labMode));$('#main-content').innerHTML=heading('02 / CONTROLLED ENVIRONMENT',labMode==='bio'?'MALWARE & ANTIVIRUS LAB.':'WEB HACKING SIMULATOR.',labMode==='bio'?'가상 파일에서 감염과 탐지를 설계하고, 격리와 복구의 원리를 배워보세요.':'공개 웹을 독립된 환경에 복제하고, 직접 수정하며 취약한 코드 패턴을 찾아보세요.','<span class="signal-dot"></span>SANDBOX MODE : ON')+`<div class="lab-tabs"><button class="lab-tab ${labMode==='web'?'active':''}" data-mode="web">${icon('code')}웹 복제 & 편집<span>WEB SANDBOX</span></button><button class="lab-tab ${labMode==='bio'?'active':''}" data-mode="bio">${icon('bug')}바이러스 & 백신<span>VIRTUAL FILE LAB</span></button><button class="text-link lab-guide" id="lab-guide">QUICK GUIDE ${icon('book')}</button></div><div id="lab-body"></div>`;document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>switchLab(b.dataset.mode));$('#lab-guide').onclick=()=>$('#guide-nav').click();if(labMode==='bio')renderBio();else renderWebLab();}
function switchLab(mode){if(mode!=='web'&&mode!=='bio')return;labMode=mode;navigate('lab');}
document.querySelectorAll('[data-lab-mode]').forEach(b=>b.onclick=()=>switchLab(b.dataset.labMode));
function renderWebLab(){
 $('#lab-body').innerHTML=`<div class="workflow-steps">${[['URL 입력','01'],['사이트 복제','02'],['자유롭게 수정','03'],['취약점 점검','04']].map(([n,c],i)=>`<div class="workflow-step ${i<step?'complete':''}"><span>${c}</span><p>${n}</p></div>`).join('')}<span class="workflow-note">SAME WEB. DIFFERENT YOU.</span></div><form class="input-panel lab-input" id="clone-form"><div class="input-wrap">${icon('link')}<input type="url" required id="clone-url" value="${esc(project.originalUrl)}" placeholder="https://example.com" aria-label="복제할 웹사이트 URL" spellcheck="false"></div><button class="primary-button" id="clone-button" type="submit">${icon('play')}사이트 복제하기</button><div class="template-actions"><span>또는 예제로 시작</span><button type="button" class="outline-button" data-template="studio">Studio</button><button type="button" class="outline-button" data-template="shop">Shop</button><button type="button" class="outline-button" data-template="login">Login</button></div><div class="scan-progress"><i></i></div></form><div class="input-help"><span>${icon('shield')}정적 HTML·CSS 복제 · 원본 서버와 분리 · 데이터 요청·폼 전송 차단</span><button class="text-link" id="import-project">IMPORT PROJECT ${icon('file')}</button><input type="file" id="project-file" accept=".json,.html" hidden></div><div class="error-message" id="clone-error" role="alert"></div>
 <div class="editor-grid"><section class="panel preview-panel">${panelHeader('CLONED WEBSITE','globe','<span class="live-badge"><span class="signal-dot"></span> LIVE</span><button class="icon-button" data-expand="preview-panel" aria-label="미리보기 확대">'+icon('expand')+'</button>')}<div class="browser-toolbar"><div class="browser-dots"><i></i><i></i><i></i></div><span class="sandbox-address" id="sandbox-address">sandbox://hexlab.local / ${esc(project.demo?'demo':new URL(project.originalUrl).hostname)}</span><button class="icon-button" id="reload-preview" aria-label="미리보기 새로고침">${icon('refresh')}</button><div class="device-switch"><button class="icon-button active" id="desktop-preview" aria-label="데스크톱 미리보기">${icon('desktop')}</button><button class="icon-button" id="mobile-preview" aria-label="모바일 미리보기">${icon('mobile')}</button></div></div><div class="iframe-container" id="iframe-container"><iframe id="preview-frame" title="격리된 사이트 미리보기" sandbox="allow-scripts" referrerpolicy="no-referrer"></iframe></div><div class="panel-status"><span id="preview-source">${esc(project.source)}</span><span>ISOLATED / NO SERVER ACCESS</span></div></section>
 <section class="panel code-panel">${panelHeader('CODE EDITOR','code','<button class="icon-button" data-expand="code-panel" aria-label="코드 편집기 확대">'+icon('expand')+'</button>')}<div class="editor-toolbar"><div class="code-tabs">${['html','css','js'].map(t=>`<button data-editor-tab="${t}" class="${t===editorTab?'active':''}">${t.toUpperCase()}</button>`).join('')}</div><label class="switch-label"><input type="checkbox" id="auto-apply" ${autoApply?'checked':''}><span class="switch"></span>Auto apply</label><button class="primary-button small" id="apply-code">${icon('check')}적용하기</button></div><div class="editor-filename"><span id="editor-filename">${editorTab==='html'?'index.html':editorTab==='css'?'style.css':'script.js'}</span><span id="editor-char-count"></span></div><div class="code-editor"><div class="line-numbers" id="line-numbers" aria-hidden="true"></div><div class="code-layer"><pre id="highlight-code" aria-hidden="true"></pre><textarea id="code-input" aria-label="${editorTab.toUpperCase()} 코드 편집기" spellcheck="false" autocapitalize="off" wrap="off"></textarea></div></div><div class="panel-status"><span>UTF-8 <span class="footer-slash">/</span> ${editorTab.toUpperCase()}</span><button class="text-link" id="export-project">${icon('download')}EXPORT PROJECT</button></div></section></div>
 <div class="lab-bottom-grid"><section class="panel console-panel">${panelHeader('ATTACK CONSOLE','terminal','<button class="text-link" id="clear-console">CLEAR</button>')}<div class="console-tabs"><button class="active" id="manual-tab">Manual console</button><button id="auto-scan">${icon('scan')}코드 분석</button><button id="modules-button">Scenarios</button></div><pre id="console-output"></pre><form class="console-prompt" id="console-form"><span>hexlab@web-sim:~$</span><input id="console-input" aria-label="실습 콘솔 명령어" autocomplete="off" spellcheck="false" placeholder="help"><button class="icon-button" aria-label="명령 실행">${icon('play')}</button></form></section>
 <section class="panel local-results-panel">${panelHeader('CODE INSPECTION','bug','<span class="count" id="local-issue-count">—</span>')}<div class="code-results" id="local-results"><div class="empty-state">${icon('scan')}<p>코드 분석을 실행해 위험한 패턴을 찾아보세요.</p><span>원본 사이트의 취약점 판정과는 별도입니다.</span></div></div></section>
 <section class="panel sandbox-panel">${panelHeader('SANDBOX INFO','shield')}<div class="info-table"><div class="info-row"><span>Status</span><span class="state-text"><span class="signal-dot"></span>Running</span></div><div class="info-row"><span>Environment</span><span>Isolated iframe</span></div><div class="info-row"><span>Data requests</span><span>Blocked</span></div><div class="info-row"><span>Save location</span><span>This browser</span></div></div><button class="outline-button reset-button" id="reset-project">${icon('refresh')}예제로 초기화</button><div class="sandbox-tip"><span>// OPERATOR TIP</span><p>JS 탭의 <code>innerHTML</code>을 <code>textContent</code>로 바꾼 뒤 다시 분석해보세요.</p></div></section></div>`;
 $('#clone-form').onsubmit=async e=>{e.preventDefault();await cloneTarget($('#clone-url').value).catch(()=>{});};document.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>loadTemplate(b.dataset.template));document.querySelectorAll('[data-editor-tab]').forEach(b=>b.onclick=()=>{editorTab=b.dataset.editorTab;renderWebLab();});$('#code-input').value=project[editorTab];updateHighlight();$('#code-input').oninput=()=>{project[editorTab]=$('#code-input').value;updateHighlight();saveProject();clearTimeout(editingTimer);if(autoApply)editingTimer=setTimeout(()=>applyPreview(),450);markMission('edit');};$('#code-input').onscroll=syncCodeScroll;$('#code-input').onkeydown=e=>{if(e.key==='Tab'){e.preventDefault();const t=e.target;const start=t.selectionStart;const end=t.selectionEnd;t.setRangeText('  ',start,end,'end');t.dispatchEvent(new Event('input'));}if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();applyPreview();toast('변경 사항을 적용했습니다.');}};$('#auto-apply').onchange=e=>{autoApply=e.target.checked;if(autoApply)applyPreview();};$('#apply-code').onclick=()=>{applyPreview();markMission('edit');toast('미리보기에 변경 사항을 적용했습니다.');};$('#reload-preview').onclick=applyPreview;$('#desktop-preview').onclick=()=>setDevice(false);$('#mobile-preview').onclick=()=>setDevice(true);$('#export-project').onclick=()=>{download(JSON.stringify(project,null,2),'hexlab-project.json');toast('프로젝트를 내보냈습니다.');};$('#import-project').onclick=()=>$('#project-file').click();$('#project-file').onchange=importProject;$('#reset-project').onclick=()=>openDialog('<h2>예제로 초기화할까요?</h2><p>현재 편집 내용이 NEXUS 예제로 바뀝니다. 먼저 프로젝트를 내보내면 나중에 다시 가져올 수 있습니다.</p><button class="primary-button" id="confirm-reset">예제로 초기화</button>');$('#reset-project').addEventListener('click',()=>$('#confirm-reset').onclick=()=>{$('#detail-dialog').close();loadTemplate('studio');});$('#clear-console').onclick=()=>{consoleLines=[];renderConsole();};$('#manual-tab').onclick=()=>$('#console-input').focus();$('#auto-scan').onclick=inspectProject;$('#modules-button').onclick=showScenarios;$('#console-form').onsubmit=e=>{e.preventDefault();const command=$('#console-input').value.trim();$('#console-input').value='';executeCommand(command);};document.querySelectorAll('[data-expand]').forEach(b=>b.onclick=()=>$('.'+b.dataset.expand).classList.toggle('expanded-panel'));applyPreview(false);renderConsole();if(localIssues.length)renderLocalIssues();
}
function saveProject(){try{localStorage.setItem('hexlab-project',JSON.stringify(project));}catch{toast('프로젝트가 커서 자동 저장되지 않았습니다. 내보내기를 사용하세요.');}}
function sanitizeHTML(html,base=''){const doc=new DOMParser().parseFromString(html,'text/html');doc.querySelectorAll('script,iframe,object,embed,base,meta,link[rel="import"],link[rel="stylesheet"],link[rel="preload"]').forEach(n=>n.remove());doc.querySelectorAll('*').forEach(el=>{for(const a of [...el.attributes]){if(/^on/i.test(a.name)||['action','formaction','srcdoc','integrity','nonce','srcset','ping'].includes(a.name))el.removeAttribute(a.name);if(['src','href','poster','xlink:href'].includes(a.name)){const raw=a.value.trim();if(/^\s*(javascript|vbscript|file|blob):/i.test(raw)){el.removeAttribute(a.name);continue;}if(a.name==='href'&&el.tagName==='A'){el.setAttribute('href','#');continue;}if(base&&!raw.startsWith('data:')){try{el.setAttribute(a.name,new URL(raw,base).href);}catch{el.removeAttribute(a.name);}}}}if(el.tagName==='FORM')el.setAttribute('onsubmit','return false');});return'<!doctype html>\n'+doc.documentElement.outerHTML;}
function previewDocument(source=project){let html=sanitizeHTML(source.html,source.baseUrl);const safeCSS=source.css.replace(/<\/style/gi,'<\\/style');const safeJS=source.js.replace(/<\/script/gi,'<\\/script');const csp="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data: https:; font-src data: https:; connect-src 'none'; form-action 'none'; base-uri 'none';";const guards=`<meta http-equiv="Content-Security-Policy" content="${csp}"><meta name="referrer" content="no-referrer"><style>${safeCSS}</style>`;html=html.replace(/<head[^>]*>/i,m=>m+guards);const bridge=`<script>document.addEventListener('click',function(e){const a=e.target.closest('a');if(a)e.preventDefault();});document.addEventListener('submit',e=>e.preventDefault());window.addEventListener('error',e=>parent.postMessage({type:'hexlab-error',message:String(e.message).slice(0,240)},'*'));<\/script>`;return html.replace(/<\/body>/i,bridge+`<script>${safeJS}<\/script></body>`);}
function applyPreview(commit=true){if(!$('#preview-frame'))return;if(commit)appliedProject={...project};$('#preview-frame').srcdoc=previewDocument(appliedProject);step=Math.max(step,3);}
function setDevice(mobile){$('#iframe-container').classList.toggle('mobile',mobile);$('#desktop-preview').classList.toggle('active',!mobile);$('#mobile-preview').classList.toggle('active',mobile);}
function updateHighlight(){const code=$('#code-input').value;$('#line-numbers').textContent=Array.from({length:code.split('\n').length},(_,i)=>i+1).join('\n');let escaped=esc(code);if(editorTab==='html')escaped=escaped.replace(/(&lt;\/?[\w-]+)/g,'<span class="syntax-tag">$1</span>').replace(/(&quot;.*?&quot;)/g,'<span class="syntax-string">$1</span>');else escaped=escaped.replace(/(&#39;.*?&#39;|&quot;.*?&quot;)/g,'<span class="syntax-string">$1</span>').replace(/\b(const|let|function|return|if|new|document|window)\b/g,'<span class="syntax-keyword">$1</span>');$('#highlight-code').innerHTML=escaped+'\n';$('#editor-char-count').textContent=code.length.toLocaleString()+' chars';syncCodeScroll();}
function syncCodeScroll(){const t=$('#code-input');$('#highlight-code').scrollTop=t.scrollTop;$('#highlight-code').scrollLeft=t.scrollLeft;$('#line-numbers').scrollTop=t.scrollTop;}
function renderConsole(){if(!$('#console-output'))return;$('#console-output').textContent=consoleLines.join('\n');$('#console-output').scrollTop=$('#console-output').scrollHeight;}
function logConsole(line){consoleLines.push(line);consoleLines=consoleLines.slice(-100);renderConsole();}
function executeCommand(command){if(!command)return;logConsole('hexlab@web-sim:~$ '+command);if(command==='help')logConsole('Commands: help, scan, status, clear, reset\nConsole commands act on this sandbox only.');else if(command==='scan')inspectProject();else if(command==='status')logConsole('[+] Sandbox running | network isolated\n[i] Source: '+project.source+'\n[i] HTML '+project.html.length+' chars / CSS '+project.css.length+' / JS '+project.js.length);else if(command==='clear'){consoleLines=[];renderConsole();}else if(command==='reset')$('#reset-project').click();else logConsole('[!] Unknown command. Type help.');}
function inspectProject(){localIssues=inspectCode(project);step=4;logConsole('[+] Inspecting local HTML / CSS / JS...');for(const i of localIssues)logConsole('['+i.severity.toUpperCase()+'] '+i.title);logConsole('[✓] '+localIssues.length+' code pattern(s) found. No requests sent to original site.');renderLocalIssues();toast('실습 코드 분석을 완료했습니다.');return{issues:localIssues};}
function renderLocalIssues(){if(!$('#local-results'))return;$('#local-issue-count').textContent=localIssues.length;$('#local-results').innerHTML=localIssues.length?localIssues.map(i=>`<button class="local-issue" data-local-issue="${i.id}"><span class="severity-label ${i.severity}">${i.severity.toUpperCase()}</span><span>${esc(i.title)}<small>${esc(i.description)}</small></span>${icon('chevron')}</button>`).join(''):'<div class="empty-state">'+icon('shield')+'<p>검사한 위험 패턴이 발견되지 않았습니다.</p><span>전체 보안 검증을 의미하지 않습니다.</span></div>';document.querySelectorAll('[data-local-issue]').forEach(b=>b.onclick=()=>{const i=localIssues.find(i=>i.id===b.dataset.localIssue);openDialog(`<span class="severity-label ${i.severity}">${i.severity.toUpperCase()}</span><h2>${esc(i.title)}</h2><p>${esc(i.description)}</p><pre>${esc(i.evidence)}</pre><h3>FIX IT</h3><p>${esc(i.fix)}</p>`,'HEXLAB / SANDBOX CODE INSPECTION');});}
async function cloneTarget(url){const form=$('#clone-form');const b=$('#clone-button');form.classList.add('scanning');b.disabled=true;b.textContent='CLONING...';$('#clone-error').style.display='none';try{const data=await api('/api/clone',{url});project={html:sanitizeHTML(data.html,data.baseUrl),css:data.css,js:'// 원본 JavaScript는 복제하지 않습니다.\n// 실습용 코드를 여기에 작성하세요.\n',source:data.title||new URL(url).hostname,originalUrl:url,baseUrl:data.baseUrl,demo:false};appliedProject={...project};editorTab='html';localIssues=[];saveProject();logConsole('[+] Static snapshot cloned: '+url);logConsole('[i] Stylesheets: '+data.stylesLoaded+' loaded, '+data.stylesFailed+' unavailable. Original scripts removed.');if(page==='lab'&&labMode==='web')renderWebLab();toast('정적 페이지를 복제했습니다. HTML·CSS를 직접 수정해보세요.');return{title:project.source,url};}catch(e){if($('#clone-error')){$('#clone-error').textContent=e.message;$('#clone-error').style.display='block';}throw e;}finally{form.classList.remove('scanning');b.disabled=false;b.innerHTML=`${icon('play')}사이트 복제하기`;}}
function loadTemplate(type){if(type==='login')project={html:'<!doctype html>\n<html><head><title>Login demo</title></head><body><main><span class="label">NEXUS / MEMBERS ONLY</span><h1>Welcome back.</h1><p>학습용 화면입니다. 실제 계정 정보는 입력하지 마세요.</p><form><label>Email<input type="text" placeholder="demo@example.com"></label><label>Password<input type="password" placeholder="demo only"></label><button type="submit">Sign in</button></form><p id="message"></p></main></body></html>',css:initialCSS+'\nmain { max-width:450px; margin:50px auto; } label { display:block; margin:15px 0; font-size:12px; } input { display:block; width:100%; padding:12px; margin-top:8px; border:1px solid #315744; background:#0b1a12; color:#c5e1d0; }',js:"document.querySelector('form').addEventListener('submit', e => {\n  e.preventDefault();\n  document.querySelector('#message').textContent = 'Demo: no credentials are sent.';\n});",source:'예제: Login',originalUrl:'https://example.com',demo:true};else project={html:type==='shop'?initialHTML.replace('Better ideas.','Better gear.').replace('Built different.','Shop different.').replace("Let's build something ↗",'Explore collection ↗'):initialHTML,css:initialCSS,js:initialJS,source:type==='shop'?'예제: Shop':'예제: NEXUS Studio',originalUrl:'https://example.com',demo:true};appliedProject={...project};editorTab='html';localIssues=[];step=2;saveProject();renderWebLab();toast('예제 프로젝트를 불러왔습니다.');}
async function importProject(e){const f=e.target.files?.[0];if(!f)return;if(f.size>2500000){toast('2.5MB 이하의 파일을 선택하세요.');return;}try{const text=await f.text();let p;if(f.name.toLowerCase().endsWith('.html'))p={html:text,css:'',js:'',source:f.name,originalUrl:'https://example.com',demo:true};else{p=JSON.parse(text);if(['html','css','js'].some(k=>typeof p[k]!=='string'))throw new Error('프로젝트 형식이 올바르지 않습니다.');p={html:p.html,css:p.css,js:p.js,source:f.name,originalUrl:'https://example.com',demo:true};}project=p;appliedProject={...project};saveProject();editorTab='html';localIssues=[];renderWebLab();toast('프로젝트를 가져왔습니다.');}catch(err){toast(err.message);}}
function showScenarios(){openDialog('<h2>실습 시나리오</h2><h3>01 / HTML 삽입 패턴 수정</h3><p>NEXUS 예제의 JS 코드를 분석하세요. innerHTML을 textContent로 바꾸고 다시 분석하면 발견 항목이 줄어듭니다.</p><h3>02 / 동적 코드 실행 제거</h3><p>JS 탭에 <code>eval("1 + 1")</code> 같은 문자열 코드 실행을 넣고 탐지 결과를 확인하세요. 직접 계산하는 구문으로 바꿔보세요.</p><h3>03 / 로그인 폼 점검</h3><p>Login 예제로 시작해 폼 관련 수동 점검 가이드를 읽어보세요. 이 폼은 계정 정보를 전송하지 않습니다.</p>','HEXLAB / PRACTICE SCENARIOS');}
window.addEventListener('message',e=>{if(e.source!==$('#preview-frame')?.contentWindow)return;if(e.data?.type==='hexlab-error')logConsole('[JS ERROR] '+String(e.data.message).slice(0,240));});
function renderBio(){
 $('#lab-body').innerHTML=`<div class="bio-notice">${icon('shield')}<span><strong>VIRTUAL FILESYSTEM ONLY</strong> 컴퓨터 악성코드·백신의 학습용 재현 모델입니다. 실제 파일, 시스템, 네트워크에는 접근하지 않습니다.</span><span class="demo-pill">SIMULATION</span></div><div class="bio-editor-grid"><section class="panel">${panelHeader('VIRUS BUILDER','bug','<span class="panel-code">CREATE / SIMULATE</span>')}<div class="bio-controls"><div class="model-identity"><img src="./icons/${selectedVirus==='custom'?'virus':selectedVirus}.png" alt=""><div><span>MALWARE / CONCEPT MODEL</span><strong>${esc(virusConfig.name)}</strong><small>${esc(MODEL_LIBRARY.find(m=>m.key===selectedVirus)?.role||'직접 설계하는 가상 감염 규칙')}</small></div></div><label for="virus-preset">악성코드 유형</label><select id="virus-preset">${Object.entries(MALWARE_PRESETS).map(([k,v])=>`<option value="${k}" ${selectedVirus===k?'selected':''}>${esc(v.name)}</option>`).join('')}</select><p id="virus-description">${esc(MALWARE_PRESETS[selectedVirus].description)}</p><div class="bio-preset-meta">${MALWARE_PRESETS[selectedVirus].source?`<a href="${MALWARE_PRESETS[selectedVirus].source}" target="_blank" rel="noopener noreferrer">원문 / 동작 개념 출처 ${icon('external')}</a>`:'<span>커스텀 가상 동작 규칙</span>'}<span>CONCEPT MODEL</span></div><label for="virus-json">감염 동작 규칙 <span>JSON</span></label><textarea class="json-editor" id="virus-json" spellcheck="false">${esc(JSON.stringify({name:virusConfig.name,marker:virusConfig.marker,effect:virusConfig.effect,spread:virusConfig.spread},null,2))}</textarea><div class="bio-rule-help"><code>effect</code> mark / lock / replicate <span>·</span> <code>spread</code> 매 실행 1–8개</div><button class="primary-button" id="run-virus">${icon('play')}가상 감염 실행</button><div class="inline-error" id="virus-error" role="alert"></div></div></section>
 <section class="panel">${panelHeader('ANTIVIRUS BUILDER','shield','<span class="panel-code">DETECT / QUARANTINE</span>')}<div class="bio-controls"><div class="model-identity defense"><img id="selected-av-icon" src="./icons/${avPreset==='behavior'?'defender':'clamav'}.png" alt=""><div><span>ANTIVIRUS / LEARNING MODEL</span><strong id="selected-av-name">${avPreset==='behavior'?'Behavior monitor':avPreset==='custom'?'My antivirus':'Signature scanner'}</strong><small>표시자와 행위 규칙으로 탐지·격리</small></div></div><label for="av-preset">탐지 방식 프리셋</label><select id="av-preset"><option value="signature" ${avPreset==='signature'?'selected':''}>ClamAV 개념 · 시그니처 탐지</option><option value="behavior" ${avPreset==='behavior'?'selected':''}>Microsoft Defender 개념 · 행위 탐지</option><option value="custom" ${avPreset==='custom'?'selected':''}>나만의 백신 규칙</option></select><p id="av-description">${avPreset==='behavior'?'가상 잠금·복제 이벤트를 탐지합니다. 실제 Microsoft Defender 엔진을 실행하지 않습니다.':avPreset==='custom'?'나만의 표시자 또는 행위 탐지 규칙을 작성하세요.':'파일의 지정된 표시자를 탐지합니다. 실제 ClamAV 엔진을 실행하지 않습니다.'}</p><div class="bio-preset-meta"><a id="av-source" href="${avPreset==='behavior'?'https://learn.microsoft.com/en-us/defender-endpoint/behavior-monitor':'https://docs.clamav.net/manual/Signatures.html'}" target="_blank" rel="noopener noreferrer">원문 / 탐지 방식 출처 ${icon('external')}</a><span>LEARNING MODEL</span></div><label for="antivirus-json">탐지 및 대응 규칙 <span>JSON</span></label><textarea class="json-editor" id="antivirus-json" spellcheck="false">${esc(JSON.stringify(ruleSet,null,2))}</textarea><div class="bio-rule-help"><code>type</code> signature / behavior <span>·</span> <code>action</code> quarantine / report</div><button class="primary-button" id="run-av">${icon('scan')}백신 검사 실행</button><div class="inline-error" id="av-error" role="alert"></div></div></section></div>
 <div class="bio-bottom-grid"><section class="panel virtual-files-panel">${panelHeader('VIRTUAL FILESYSTEM','file','<button class="text-link" id="restore-files">'+icon('refresh')+'모두 복구</button>')}<div class="virtual-stats" id="virtual-stats"></div><div id="virtual-files"></div><div class="panel-status"><span>MEMORY ONLY <span class="footer-slash">/</span> 8 FILES</span><button class="text-link" id="export-bio">${icon('download')}EXPORT RULES</button></div></section><section class="panel bio-console-panel">${panelHeader('EXPERIMENT LOG','terminal','<span class="panel-code" id="bio-ticks">TICK : '+ticks+'</span>')}<pre id="bio-log"></pre><div class="bio-findings" id="bio-findings"></div><div class="bio-actions"><button class="outline-button" id="new-experiment">${icon('refresh')}새 실험</button><button class="outline-button" id="malware-library">${icon('book')}악성코드 도감</button></div></section></div>`;
 $('#virus-preset').onchange=e=>{selectedVirus=e.target.value;virusConfig={...MALWARE_PRESETS[selectedVirus]};renderBio();};$('#av-preset').onchange=e=>{const mode=e.target.value;avPreset=mode;if(mode==='signature'){ruleSet=[{name:'Signature-01',type:'signature',match:'HEXLAB_DEMO',action:'quarantine'}];$('#av-description').textContent='파일 내용에서 표시자를 찾는 개념 모델입니다. 실제 ClamAV 엔진을 실행하지 않습니다.';$('#av-source').href='https://docs.clamav.net/manual/Signatures.html';}else if(mode==='behavior'){ruleSet=[{name:'Lock behavior',type:'behavior',match:'file_lock',action:'quarantine'},{name:'Replication behavior',type:'behavior',match:'replication',action:'quarantine'}];$('#av-description').textContent='가상 이벤트의 잠금·복제 동작을 찾는 개념 모델입니다. 실제 Microsoft Defender 엔진을 실행하지 않습니다.';$('#av-source').href='https://learn.microsoft.com/en-us/defender-endpoint/behavior-monitor';}else{$('#av-description').textContent='표시자나 행위 이벤트를 기준으로 자신만의 탐지 규칙을 작성하세요.';}$('#antivirus-json').value=JSON.stringify(ruleSet,null,2);$('#selected-av-icon').src='./icons/'+(mode==='behavior'?'defender':'clamav')+'.png';$('#selected-av-name').textContent=mode==='behavior'?'Behavior monitor':mode==='custom'?'My antivirus':'Signature scanner';};$('#antivirus-json').oninput=()=>{avPreset='custom';$('#av-preset').value='custom';};$('#virus-json').oninput=()=>{selectedVirus='custom';$('#virus-preset').value='custom';};$('#run-virus').onclick=runVirus;$('#run-av').onclick=runAntivirus;$('#restore-files').onclick=()=>{virtualFiles=restoreVirtualFiles(virtualFiles);avFindings=[];bioLog.push('[✓] Original virtual contents restored. Infection markers removed.');updateBio();toast('가상 파일을 원래 상태로 복구했습니다.');};$('#new-experiment').onclick=()=>{virtualFiles=createVirtualFiles();ticks=0;avFindings=[];bioLog=['[+] New virtual environment initialized. 8 clean files.'];updateBio();};$('#malware-library').onclick=showMalwareLibrary;$('#export-bio').onclick=()=>{try{const virus=validateVirus(JSON.parse($('#virus-json').value));const rules=validateRules(JSON.parse($('#antivirus-json').value));download(JSON.stringify({format:'hexlab-virtual-rules-v1',virus,rules},null,2),'hexlab-simulation-rules.json');toast('가상 실험 규칙을 내보냈습니다.');}catch(e){toast('JSON 규칙을 확인하세요: '+e.message);}};updateBio();renderModelLibrary();
}
function runVirus(){try{virusConfig=validateVirus(JSON.parse($('#virus-json').value));const out=infectFiles(virtualFiles,virusConfig);virtualFiles=out.files;ticks++;bioLog.push(`[TICK ${ticks}] ${virusConfig.name}: ${out.infected} virtual file(s) affected.`);if(!out.infected)bioLog.push('[i] No clean, unquarantined files remain. Restore or start a new experiment.');$('#virus-error').textContent='';updateBio();toast(out.infected+'개 가상 파일에 감염 동작을 적용했습니다.');return{infected:out.infected,tick:ticks};}catch(e){$('#virus-error').textContent=e.message;return{error:e.message};}}
function runAntivirus(){try{ruleSet=validateRules(JSON.parse($('#antivirus-json').value));const out=scanVirtualFiles(virtualFiles,ruleSet);virtualFiles=out.files;avFindings=out.results;bioLog.push(`[SCAN] ${out.detected} detected / ${out.quarantined} quarantined.`);out.results.forEach(f=>bioLog.push(`[${f.action.toUpperCase()}] ${f.name} ← ${f.rule}`));$('#av-error').textContent='';markMission('av');updateBio();toast('가상 백신 검사를 완료했습니다.');return{detected:out.detected,quarantined:out.quarantined};}catch(e){$('#av-error').textContent=e.message;return{error:e.message};}}
function updateBio(){if(!$('#virtual-files'))return;const clean=virtualFiles.filter(f=>!f.infected).length;const infected=virtualFiles.filter(f=>f.infected&&!f.quarantined).length;const q=virtualFiles.filter(f=>f.quarantined).length;$('#virtual-stats').innerHTML=`<div><span>CLEAN</span><b>${clean.toString().padStart(2,'0')}</b></div><div class="high"><span>INFECTED</span><b>${infected.toString().padStart(2,'0')}</b></div><div class="medium"><span>QUARANTINED</span><b>${q.toString().padStart(2,'0')}</b></div>`;$('#virtual-files').innerHTML=`<div class="virtual-file-row table-head"><span>VIRTUAL FILE</span><span>STATE</span><span>ACTION</span></div>`+virtualFiles.map((f,i)=>`<div class="virtual-file-row"><button data-open-virtual="${i}">${icon('file')}${esc(f.name)}</button><span class="${f.quarantined?'medium':f.infected?'high':'low'}">${f.quarantined?'QUARANTINED':f.locked?'LOCKED':f.infected?'INFECTED':'CLEAN'}</span><span>${f.quarantined?`<button class="text-link" data-restore-virtual="${i}">복구</button>`:'—'}</span></div>`).join('');$('#bio-log').textContent=bioLog.slice(-70).join('\n');$('#bio-log').scrollTop=$('#bio-log').scrollHeight;$('#bio-ticks').textContent='TICK : '+ticks;$('#bio-findings').innerHTML=avFindings.length?`<span>// DETECTION RESULTS</span>${avFindings.map(f=>`<p><b>${esc(f.name)}</b> <span>${esc(f.rule)}</span></p>`).join('')}`:'<span>// WAITING FOR NEXT EXPERIMENT_</span>';document.querySelectorAll('[data-restore-virtual]').forEach(b=>b.onclick=()=>{const i=+b.dataset.restoreVirtual;virtualFiles[i]=restoreVirtualFiles([virtualFiles[i]])[0];bioLog.push('[✓] Restored: '+virtualFiles[i].name);updateBio();});document.querySelectorAll('[data-open-virtual]').forEach(b=>b.onclick=()=>{const f=virtualFiles[+b.dataset.openVirtual];openDialog(`<h2>${esc(f.name)}</h2><p>가상 파일 · ${f.quarantined?'격리됨':f.locked?'잠금 표시':f.infected?'감염 표시':'정상'}</p><h3>CONTENTS IN MEMORY</h3><pre>${esc(f.content)}</pre><h3>SIMULATED EVENTS</h3><pre>${esc(f.events.join('\n')||'No events')}</pre>`,'HEXLAB / VIRTUAL FILE INSPECTOR');});}
function showMalwareLibrary(){openDialog(`<span class="demo-pill">REFERENCE / CONCEPTS</span><h2>컴퓨터 악성코드 & 백신 도감</h2><p>여기의 실험은 아래 동작 개념을 인용한 재현 모델입니다. 원본 악성코드, 실제 감염 기능 또는 제품 엔진을 포함하지 않습니다.</p>${Object.entries(MALWARE_PRESETS).filter(([k])=>k!=='custom').map(([k,v])=>`<h3>${esc(v.name)}</h3><p>${esc(v.description)}</p><a class="text-link" href="${v.source}" target="_blank" rel="noopener noreferrer">공식 참고 자료 ${icon('external')}</a>`).join('')}<h3>ClamAV / 시그니처</h3><p>파일의 패턴과 시그니처를 기준으로 위협을 탐지하는 방식을 배웁니다.</p><a class="text-link" href="https://docs.clamav.net/manual/Signatures.html" target="_blank" rel="noopener noreferrer">ClamAV 공식 문서</a><h3>Microsoft Defender / 행위 모니터링</h3><p>프로세스·파일·서비스 활동을 관찰해 의심스러운 동작을 탐지하는 방식을 배웁니다.</p><a class="text-link" href="https://learn.microsoft.com/en-us/defender-endpoint/behavior-monitor" target="_blank" rel="noopener noreferrer">Microsoft 공식 문서</a>`,'HEXLAB / MALWARE & DEFENSE LIBRARY');}
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.expanded-panel').forEach(p=>p.classList.remove('expanded-panel'));});

function renderModelLibrary(){
 const section=document.createElement('section');section.className='model-library';section.innerHTML='<div class="model-library-heading"><div><div class="eyebrow">// MALWARE & DEFENSE INTELLIGENCE</div><h2>알고 실험하면, 더 잘 방어할 수 있습니다.</h2></div><span>6 CONCEPT MODELS</span></div><div class="model-card-grid">'+MODEL_LIBRARY.map(m=>`<article class="model-card ${['defender','clamav'].includes(m.key)?'defense':''}"><div class="model-card-top"><img src="${m.icon}" alt="${esc(m.name)}의 역할을 상징하는 3D 아이콘" loading="lazy"><span>${m.category}</span></div><h3>${esc(m.name)}</h3><div class="model-label">${esc(m.label)}</div><strong>${esc(m.role)}</strong><p>${esc(m.function)}</p><div class="model-card-bottom"><button class="text-link" data-model-detail="${m.key}">역할 & 실습 설명 ${icon('book')}</button><button class="outline-button" data-load-model="${m.key}">모델 사용</button></div></article>`).join('')+'</div><p class="model-library-note">아이콘은 각 역할을 상징하는 창작 에셋입니다. 제품 공식 로고가 아니며, 학습 모델과 실제 제품·악성코드를 구분합니다.</p>';
 $('#lab-body').append(section);
 document.querySelectorAll('[data-model-detail]').forEach(b=>b.onclick=()=>{const m=MODEL_LIBRARY.find(m=>m.key===b.dataset.modelDetail);openDialog(`<div class="model-dialog-identity"><img src="${m.icon}" alt=""><div><span class="eyebrow">${m.category}</span><h2>${esc(m.name)}</h2><p>${esc(m.label)}</p></div></div><h3>역할과 동작 원리</h3><p>${esc(m.function)}</p><h3>이 실습에서의 재현</h3><p>${esc(m.simulation)}</p><a class="text-link" href="${m.source}" target="_blank" rel="noopener noreferrer">${esc(m.sourceName)} ${icon('external')}</a>`,'HEXLAB / MODEL INTELLIGENCE');});
 document.querySelectorAll('[data-load-model]').forEach(b=>b.onclick=()=>{const key=b.dataset.loadModel;if(MALWARE_PRESETS[key]){selectedVirus=key;virusConfig={...MALWARE_PRESETS[key]};}else if(key==='defender'){avPreset='behavior';ruleSet=[{name:'Lock behavior',type:'behavior',match:'file_lock',action:'quarantine'},{name:'Replication behavior',type:'behavior',match:'replication',action:'quarantine'}];}else{avPreset='signature';ruleSet=[{name:'Signature-01',type:'signature',match:'HEXLAB_DEMO',action:'quarantine'}];}renderBio();$('.bio-editor-grid').scrollIntoView({behavior:'smooth',block:'start'});toast('선택한 개념 모델을 불러왔습니다.');});
}

const modelContext=document.modelContext;if(modelContext?.registerTool){const lifecycle=new AbortController();const register=t=>{try{Promise.resolve(modelContext.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'navigate_hexlab',title:'실습 화면 열기',description:'보안 분석, 웹·가상 파일 실습 및 코드 연출 화면을 엽니다.',inputSchema:{type:'object',properties:{screen:{type:'string',enum:['intro','scan','web','bio','code']}},required:['screen'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!['intro','scan','web','bio','code'].includes(input?.screen))throw new Error('Invalid screen');if(['web','bio'].includes(input.screen)){labMode=input.screen; navigate('lab');}else navigate(input.screen);return{screen:input.screen};}});register({name:'inspect_sandbox_code',title:'실습 코드 검사',description:'현재 실습 프로젝트의 위험한 코드 패턴을 검사합니다. 외부 사이트에 요청하지 않습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||Object.keys(input).length)throw new Error('No arguments expected');labMode='web';navigate('lab');return inspectProject();}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
decorate();$('#report-count').textContent=String(historyReports.length).padStart(2,'0');navigate(routeFromLocation(),false);function updateClock(){$('#local-time').textContent=new Date().toLocaleTimeString('en-GB',{timeZone:'Asia/Seoul'})+' KST';}updateClock();setInterval(updateClock,1000);
