const allowedOrigins=new Set(['https://leejinho970715-star.github.io','http://127.0.0.1:4173','http://localhost:4173']);
const visits=new Map();
export function isPublicAddress(value){
 if(value.includes(':')){const ip=value.toLowerCase();return /^[23][0-9a-f]{0,3}:/.test(ip)&&!ip.startsWith('2001:db8:')&&!ip.startsWith('2002:')&&!ip.startsWith('2001:0:');}
 const p=value.split('.').map(Number);if(p.length!==4||p.some(n=>!Number.isInteger(n)||n<0||n>255))return false;
 return !(p[0]===0||p[0]===10||p[0]===127||p[0]>=224||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&(p[1]===168||p[1]===0))||(p[0]===100&&p[1]>=64&&p[1]<=127)||(p[0]===198&&(p[1]===18||p[1]===19))||(p[0]===198&&p[1]===51&&p[2]===100)||(p[0]===203&&p[1]===0&&p[2]===113));
}
export function validateTarget(value){
 if(typeof value!=='string'||value.length>2048)throw new Error('올바른 공개 웹사이트 URL을 입력하세요.');let u;try{u=new URL(value);}catch{throw new Error('https://로 시작하는 URL을 입력하세요.');}
 if(!['http:','https:'].includes(u.protocol)||u.username||u.password||(u.port&&!['80','443'].includes(u.port)))throw new Error('HTTP/HTTPS 공개 웹사이트의 기본 포트만 지원합니다.');
 const host=u.hostname.toLowerCase().replace(/\.$/,'');if(!host.includes('.')||host.includes(':')||/^\d+(\.\d+){3}$/.test(host)||host==='localhost'||/\.(local|localhost|internal|lan|test|invalid|example)$/.test(host)||!/^[a-z0-9.-]+$/.test(host))throw new Error('내부 주소·IP 주소는 지원하지 않습니다. 공개 도메인을 입력하세요.');
 u.hostname=host;u.hash='';return u;
}
async function resolvePublic(hostname){const answers=await Promise.all(['A','AAAA'].map(async type=>{const r=await fetch(`https://cloudflare-dns.com/dns-query?name=${encodeURIComponent(hostname)}&type=${type}`,{headers:{Accept:'application/dns-json'},signal:AbortSignal.timeout(5000)});if(!r.ok)throw new Error('DNS 확인에 실패했습니다.');const d=await r.json();return(d.Answer||[]).filter(a=>a.type===1||a.type===28).map(a=>a.data);}));const ips=answers.flat();if(!ips.length||ips.some(ip=>!isPublicAddress(ip)))throw new Error('공개 네트워크 주소로 확인할 수 없는 대상입니다.');return ips;}
export async function safeFetch(value,env={},maxBytes=1800000){let url=validateTarget(value);const signal=AbortSignal.timeout(16000);for(let n=0;n<5;n++){const addresses=await resolvePublic(url.hostname);const init={method:'GET',redirect:'manual',headers:{'User-Agent':'HEXLAB-PassiveCheck/1.0','Accept':'text/html,text/css;q=0.9,*/*;q=0.5'},signal};const response=env.UPSTREAM_FETCH?await env.UPSTREAM_FETCH(url,init,addresses):await fetch(url,init);if(response.status>=300&&response.status<400&&response.headers.get('location')){await response.body?.cancel();url=validateTarget(new URL(response.headers.get('location'),url).href);continue;}if(response.status>=400){await response.body?.cancel();throw new Error(`대상 사이트가 HTTP ${response.status}로 응답했습니다. 접근 가능한 공개 페이지를 사용하세요.`);}const reader=response.body?.getReader();let total=0;const chunks=[];if(reader){while(true){const {value:chunk,done}=await reader.read();if(done)break;total+=chunk.length;if(total>maxBytes){await reader.cancel();throw new Error('페이지가 처리 가능한 크기를 초과했습니다.');}chunks.push(chunk);}}const bytes=new Uint8Array(total);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}return{response,text:new TextDecoder().decode(bytes),url:url.href};}throw new Error('리디렉션이 너무 많습니다. 최종 URL을 입력하세요.');}
export function analyzeResponse({response,text,url},originalUrl,elapsed){const h=response.headers;const issues=[];const add=(id,severity,title,description,evidence,fix,weight)=>issues.push({id,severity,title,description,evidence,fix,weight});
 if(new URL(url).protocol!=='https:')add('https','high','Unencrypted HTTP Connection','페이지가 암호화되지 않은 HTTP로 제공됩니다.',`Final URL: ${url}`,'HTTPS를 활성화하고 HTTP 요청을 HTTPS로 이동시키세요.',25);
 const csp=h.get('content-security-policy');if(!csp)add('csp','medium','Missing Content Security Policy','콘텐츠 출처를 제한하는 CSP 헤더가 관측되지 않았습니다.','Content-Security-Policy: not observed','콘텐츠 출처에 맞는 CSP 정책을 설정하고 Report-Only로 먼저 검증하세요.',15);
 if(!h.get('x-frame-options')&&!/frame-ancestors/i.test(csp||''))add('frame','medium','Missing Frame Protection','프레임 삽입을 제한하는 헤더가 관측되지 않았습니다.','X-Frame-Options / CSP frame-ancestors: not observed',"CSP에 frame-ancestors 'self' 또는 'none'을 설정하세요.",10);
 if(h.get('x-content-type-options')?.toLowerCase()!=='nosniff')add('nosniff','low','MIME Sniffing Protection Missing','MIME 타입 추측 방지 설정을 확인할 수 없습니다.','X-Content-Type-Options: nosniff not observed','X-Content-Type-Options: nosniff 헤더를 추가하세요.',10);
 if(new URL(url).protocol==='https:'&&!h.get('strict-transport-security'))add('hsts','low','No HSTS Header','HTTPS 연결 강제 정책이 관측되지 않았습니다.','Strict-Transport-Security: not observed','HTTPS 동작 확인 후 HSTS 정책을 적용하세요.',10);
 if(!h.get('referrer-policy'))add('referrer','low','Referrer Policy Not Set','출처 정보 전달 정책이 명시되지 않았습니다.','Referrer-Policy: not observed','서비스 요구에 맞는 Referrer-Policy를 명시하세요.',5);
 const cookies=h.getSetCookie?h.getSetCookie():(h.get('set-cookie')?[h.get('set-cookie')]:[]);if(cookies.some(c=>!/;\s*secure(?:;|$)/i.test(c)))add('cookie','medium','Cookie Missing Secure Flag','응답 쿠키 중 Secure 속성이 없는 항목이 관측됐습니다.','Set-Cookie: [values redacted]; missing Secure','HTTPS 세션 쿠키에 Secure 속성을 추가하세요.',10);
 if(h.get('x-powered-by'))add('disclosure','info','Runtime Information Disclosed','런타임 정보가 응답 헤더에 노출됩니다.',`X-Powered-By: ${h.get('x-powered-by').slice(0,160)}`,'불필요한 버전 헤더 노출을 줄이세요. 노출 자체가 취약점 확정은 아닙니다.',3);
 const tech=[];if(/nginx/i.test(h.get('server')||''))tech.push('Nginx');if(/cloudflare/i.test(h.get('server')||''))tech.push('Cloudflare');if(/php/i.test(h.get('x-powered-by')||''))tech.push('PHP');if(/jquery[.-]/i.test(text))tech.push('jQuery');if(/__NEXT_DATA__|\/_next\//.test(text))tech.push('Next.js');if(/wp-content\//.test(text))tech.push('WordPress');
 const score=Math.max(0,100-issues.reduce((s,i)=>s+i.weight,0));return{demo:false,url:originalUrl,finalUrl:url,score,grade:score>=90?'A':score>=70?'B':score>=50?'C':'D',risk:score>=90?'LOW':score>=70?'MODERATE':score>=50?'ELEVATED':'HIGH',status:response.status,server:h.get('server')?.slice(0,120)||'Not disclosed',title:text.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.slice(0,180)||'',elapsed:Math.round(elapsed*100)/100,scannedAt:new Date().toISOString(),issues,technologies:tech,checks:[{name:'Protocol',result:new URL(url).protocol==='https:'?'HTTPS':'HTTP',detail:new URL(url).protocol==='https:'?'TLS 사용':'암호화 없음'},{name:'HTTP response',result:String(response.status),detail:'GET 응답 상태'},{name:'Redirect',result:url===originalUrl?'None':'Followed',detail:url===originalUrl?'원본 URL':'최종 URL 확인'},{name:'Content type',result:(h.get('content-type')||'unknown').split(';')[0].slice(0,30),detail:'응답 문서 형식'}]};
}
async function clonePage(target,env){const page=await safeFetch(target,env);if(!/text\/html/i.test(page.response.headers.get('content-type')||''))throw new Error('HTML 웹페이지만 복제할 수 있습니다.');const baseHref=page.text.match(/<base\b[^>]*href\s*=\s*["']([^"']+)/i)?.[1];let base=page.url;try{if(baseHref)base=new URL(baseHref,page.url).href;}catch{}const sheets=[...page.text.matchAll(/<link\b[^>]*>/gi)].filter(m=>/rel\s*=\s*["']?stylesheet/i.test(m[0])).map(m=>m[0].match(/href\s*=\s*["']([^"']+)/i)?.[1]).filter(Boolean).slice(0,4);const results=await Promise.allSettled(sheets.map(async href=>{const css=await safeFetch(new URL(href,base).href,env,350000);return css.text.replace(/url\(\s*(['"]?)(?!data:)([^)'"\s]+)\1\s*\)/gi,(_,q,src)=>{try{return`url("${new URL(src,css.url).href.replace(/"/g,'%22')}")`;}catch{return'url("")';}});}));return{html:page.text,css:results.filter(r=>r.status==='fulfilled').map(r=>r.value).join('\n'),baseUrl:base,originalUrl:target,title:page.text.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||new URL(target).hostname,stylesLoaded:results.filter(r=>r.status==='fulfilled').length,stylesFailed:results.filter(r=>r.status==='rejected').length,notice:'공개 정적 HTML과 최대 4개 스타일시트를 복제합니다. 원본 JavaScript, 로그인·서버 기능은 포함하지 않습니다.'};}
export default{async fetch(request,env={}){const u=new URL(request.url);const origin=request.headers.get('origin');const cors={'Vary':'Origin',...(origin&&allowedOrigins.has(origin)?{'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Methods':'POST, GET, OPTIONS','Access-Control-Allow-Headers':'Content-Type','Access-Control-Max-Age':'86400'}:{})};const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...cors}});if(request.method==='OPTIONS')return new Response(null,{status:allowedOrigins.has(origin)?204:403,headers:cors});if(u.pathname==='/api/health'||u.pathname==='/')return json({service:'HEXLAB API',status:'operational',mode:'passive-http'});if(!['/api/scan','/api/clone'].includes(u.pathname))return json({error:'Not found'},404);if(origin&&!allowedOrigins.has(origin))return json({error:'허용되지 않은 웹사이트의 요청입니다.'},403);if(request.method!=='POST')return json({error:'POST 요청이 필요합니다.'},405);const key=request.headers.get('cf-connecting-ip')||'local';const now=Date.now();const recent=(visits.get(key)||[]).filter(t=>now-t<60000);if(recent.length>=8)return json({error:'요청이 많습니다. 잠시 후 다시 시도하세요.'},429);recent.push(now);visits.set(key,recent);if(visits.size>2000)visits.delete(visits.keys().next().value);try{const raw=await request.text();if(raw.length>3000)return json({error:'요청이 너무 큽니다.'},413);const input=JSON.parse(raw);const target=validateTarget(input.url).href;const start=performance.now();if(u.pathname==='/api/clone')return json(await clonePage(target,env));const fetched=await safeFetch(target,env);return json(analyzeResponse(fetched,target,(performance.now()-start)/1000));}catch(e){return json({error:e.name==='TimeoutError'||e.name==='AbortError'?'사이트 응답 시간이 초과되었습니다. 다시 시도하거나 다른 페이지를 사용하세요.':e.message||'요청을 처리할 수 없습니다.'},400);}}};
